port: 8080
static_dir: /Users/liuhailong/Documents/workspace/pingmesh/code/pingmesh-front-v2/dist
mysql:
    host: 127.0.0.1
    port: 3306
    user: root
    password: root123
    database: pingmesh
prometheus:
    base_url: http://127.0.0.1:9090
idcs:
    - code: BJ12
      name: 北京昌平
      enable: true
    - code: BJ13
      name: 北京亦庄
      enable: true
    - code: SH22
      name: 上海虹桥
      enable: false
    - code: SH23
      name: 上海宝山
      enable: true
    - code: SZ32
      name: 深圳宝安
      enable: true
    - code: SZ33
      name: 深圳福田
      enable: false
idc_links:
    - source: BJ12
      target: BJ13
      enable: true
    - source: SH22
      target: SH23
      enable: false
    - source: BJ12
      target: SH22
      enable: false
    - source: BJ12
      target: SZ32
      enable: true
    - source: BJ13
      target: SH23
      enable: true
    - source: BJ13
      target: SZ33
      enable: false
    - source: SH22
      target: BJ12
      enable: false
    - source: SH22
      target: SZ32
      enable: false
    - source: SH23
      target: BJ13
      enable: true
    - source: SH23
      target: SZ33
      enable: false
    - source: SZ32
      target: BJ12
      enable: true
    - source: SZ32
      target: SH22
      enable: true
    - source: SZ32
      target: SZ33
      enable: true
    - source: SZ33
      target: SH23
      enable: false
latency_levels_for_idc_inner:
    warn: 15
    alarm: 100
lost_levels_for_idc_inner:
    warn: 0.01
    alarm: 0.1
latency_levels_for_idc_between:
    warn: 30
    alarm: 100
lost_levels_for_idc_between:
    warn: 5
    alarm: 10
metrics_meta:
    - metric: ping_idc_latency_avg
      type: latency
      scope: idc
      category: avg
      description: ""
      status: show
      strategy: ""
    - metric: ping_idc_latency_max
      type: latency
      scope: idc
      category: max
      description: ""
      status: show
      strategy: ""
    - metric: ping_idc_latency_p99
      type: latency
      scope: idc
      category: p99
      description: ""
      status: show
      strategy: ""
    - metric: ping_idc_link_status
      type: latency
      scope: idc
      category: raw
      description: 机房间链路状态
      status: show
      strategy: ""
    - metric: ping_idc_lost
      type: loss
      scope: idc
      category: raw
      description: ""
      status: show
      strategy: ""
    - metric: ping_idc_lost_max
      type: loss
      scope: idc
      category: max
      description: ""
      status: show
      strategy: ""
    - metric: ping_idc_status
      type: ""
      scope: idc
      category: ""
      description: ""
      status: disable
      strategy: ""
    - metric: ping_latency_by_idc_avg
      type: latency
      scope: idc
      category: avg
      description: ""
      status: show
      strategy: "01"
    - metric: ping_latency_by_idc_max
      type: latency
      scope: idc
      category: max
      description: ""
      status: show
      strategy: "01"
    - metric: ping_latency_by_idc_p99
      type: latency
      scope: idc
      category: p99
      description: ""
      status: show
      strategy: "01"
    - metric: ping_latency_by_leaf_avg
      type: latency
      scope: leaf
      category: avg
      description: 机房内 Leaf 平均时延
      status: show
      strategy: "01"
    - metric: ping_latency_by_leaf_max
      type: latency
      scope: leaf
      category: max
      description: 机房内 Leaf 最大时延
      status: show
      strategy: "01"
    - metric: ping_latency_by_leaf_p99
      type: latency
      scope: leaf
      category: p99
      description: 机房内 Leaf P99 时延
      status: show
      strategy: "01"
    - metric: ping_latency_by_spine_avg
      type: latency
      scope: spine
      category: avg
      description: ""
      status: show
      strategy: "01"
    - metric: ping_latency_by_spine_max
      type: latency
      scope: spine
      category: max
      description: ""
      status: show
      strategy: "01"
    - metric: ping_latency_by_spine_p99
      type: latency
      scope: spine
      category: p99
      description: ""
      status: show
      strategy: "01"
    - metric: ping_latency_loss_flag
      type: ""
      scope: ""
      category: ""
      description: ""
      status: disable
      strategy: ""
    - metric: ping_latency_ms
      type: latency
      scope: ""
      category: raw
      description: 唯一原始值
      status: show
      strategy: ""
    - metric: ping_latency_ms_avg_by_idc
      type: latency
      scope: ""
      category: avg
      description: ""
      status: show
      strategy: ""
    - metric: ping_latency_ms_avg_by_leaf
      type: latency
      scope: leaf
      category: avg
      description: ""
      status: show
      strategy: ""
    - metric: ping_latency_ms_max_by_idc
      type: latency
      scope: ""
      category: max
      description: ""
      status: show
      strategy: ""
    - metric: ping_latency_ms_max_by_leaf
      type: latency
      scope: leaf
      category: max
      description: ""
      status: show
      strategy: ""
    - metric: ping_latency_ms_p99_by_idc
      type: latency
      scope: ""
      category: p99
      description: ""
      status: show
      strategy: ""
    - metric: ping_latency_ms_p99_by_leaf
      type: latency
      scope: leaf
      category: p99
      description: ""
      status: show
      strategy: ""
    - metric: ping_latency_overall_avg
      type: latency
      scope: ""
      category: avg
      description: ""
      status: show
      strategy: "01"
    - metric: ping_latency_overall_max
      type: latency
      scope: ""
      category: max
      description: ""
      status: show
      strategy: "01"
    - metric: ping_latency_overall_p99
      type: latency
      scope: ""
      category: p99
      description: ""
      status: show
      strategy: "01"
    - metric: ping_leaf_avg
      type: latency
      scope: leaf
      category: avg
      description: Leaf 平均时延
      status: show
      strategy: ""
    - metric: ping_leaf_lost
      type: loss
      scope: leaf
      category: ""
      description: ""
      status: show
      strategy: ""
    - metric: ping_leaf_lost_max
      type: loss
      scope: leaf
      category: max
      description: ""
      status: show
      strategy: ""
    - metric: ping_leaf_max
      type: latency
      scope: leaf
      category: max
      description: Leaf 最大时延
      status: show
      strategy: ""
    - metric: ping_leaf_max_all
      type: latency
      scope: leaf
      category: max
      description: 全机房 Leaf 最大时延
      status: show
      strategy: ""
    - metric: ping_leaf_p99
      type: latency
      scope: leaf
      category: p99
      description: Leaf P99 时延
      status: show
      strategy: ""
    - metric: ping_loss_by_idc
      type: ""
      scope: ""
      category: ""
      description: ""
      status: disable
      strategy: ""
    - metric: ping_loss_by_leaf
      type: ""
      scope: ""
      category: ""
      description: ""
      status: disable
      strategy: ""
    - metric: ping_loss_by_spine
      type: ""
      scope: ""
      category: ""
      description: ""
      status: disable
      strategy: ""
    - metric: ping_loss_flag
      type: ""
      scope: ""
      category: ""
      description: ""
      status: disable
      strategy: ""
    - metric: ping_loss_flag_p99
      type: ""
      scope: ""
      category: ""
      description: ""
      status: disable
      strategy: ""
    - metric: ping_lost_by_idc
      type: loss
      scope: ""
      category: ""
      description: ""
      status: show
      strategy: ""
    - metric: ping_lost_by_idc_max
      type: loss
      scope: idc
      category: max
      description: ""
      status: show
      strategy: ""
    - metric: ping_lost_by_leaf
      type: loss
      scope: leaf
      category: raw
      description: Leaf 丢包率
      status: show
      strategy: ""
    - metric: ping_lost_by_leaf_avg
      type: loss
      scope: leaf
      category: avg
      description: ""
      status: show
      strategy: ""
    - metric: ping_lost_by_leaf_max
      type: loss
      scope: leaf
      category: max
      description: ""
      status: show
      strategy: ""
    - metric: ping_lost_by_spine
      type: loss
      scope: spine
      category: raw
      description: ""
      status: show
      strategy: ""
    - metric: ping_lost_by_spine_max
      type: loss
      scope: spine
      category: max
      description: ""
      status: show
      strategy: ""
    - metric: ping_lost_flag
      type: loss
      scope: ""
      category: ""
      description: ""
      status: show
      strategy: "00"
    - metric: ping_lost_overall
      type: loss
      scope: ""
      category: ""
      description: ""
      status: show
      strategy: ""
users:
    - username: liuhailong
      password: lhl123
      display_name: 刘海龙
    - username: sunran
      password: pingmesh123
      display_name: 孙冉
    - username: qiushun
      password: pingmesh123
      display_name: 邱顺
cas:
    enabled: false
    server_url: http://localhost:8443
    login_url: http://localhost:8443/login
    validate_url: http://localhost:8443/serviceValidate
    logout_url: http://localhost:8443/logout
    service_url: http://localhost:5173/api/auth/cas/callback
    frontend_callback: http://localhost:5173
    attribute_mapping:
        username: username
        display_name: displayName
        email: mail
        phone: phone
        department: department
