# ────────────────────────────────────────────────────────────────────────
# Pingmesh 指标处理
# ────────────────────────────────────────────────────────────────────────
groups:
  # ────────────────────────────────────────────────────────────────────────
  # Group 1: 机房内时延指标
  # ────────────────────────────────────────────────────────────────────────
  - name: ping_latency
    interval: 3s
    rules:
      # 机房内数据汇总：Leaf avg
      - record: ping_latency_by_leaf_avg
        expr: avg by (tidc,tspine,tleaf) (ping_latency_ms{strategy="01"} <= 400)
      # 机房内数据汇总：Leaf max
      - record: ping_latency_by_leaf_max
        expr: max by (tidc,tspine,tleaf) (ping_latency_ms{strategy="01"} <= 400)
      # 机房内数据汇总：Leaf p99
      - record: ping_latency_by_leaf_p99
        expr: quantile by (tidc,tspine,tleaf) (0.99, ping_latency_ms{strategy="01"} <= 400)

      # 机房内数据汇总：Spine avg
      - record: ping_latency_by_spine_avg
        expr: avg by (tidc,tspine) (ping_latency_ms{strategy="01"} <= 400)
      # [未使用] 机房内数据汇总：Spine max
      # - record: ping_latency_by_spine_max
      #   expr: max by (tidc,tspine) (ping_latency_ms{strategy="01"} <= 400)
      # [未使用] 机房内数据汇总：Spine p99
      # - record: ping_latency_by_spine_p99
      #   expr: quantile by (tidc,tspine) (0.99, ping_latency_ms{strategy="01"} <= 400)

      # 机房内数据汇总：idc avg
      - record: ping_latency_by_idc_avg
        expr: avg by (tidc) (ping_latency_ms{strategy="01"} <= 400)
      # 机房内数据汇总：idc max
      - record: ping_latency_by_idc_max
        expr: max by (tidc) (ping_latency_ms{strategy="01"} <= 400)
      # 机房内数据汇总：idc p99
      - record: ping_latency_by_idc_p99
        expr: quantile by (tidc) (0.99, ping_latency_ms{strategy="01"} <= 400)

      # 整体数据汇总：total avg
      - record: ping_latency_overall_avg
        expr: avg(ping_latency_ms{strategy="01"} <= 400)
      # [未使用] 整体数据汇总：total max
      # - record: ping_latency_overall_max
      #   expr: max(ping_latency_ms{strategy="01"} <= 400)
      # 整体数据汇总：total p99
      - record: ping_latency_overall_p99
        expr: quantile(0.99, ping_latency_ms{strategy="01"} <= 400)
        
  # ────────────────────────────────────────────────────────────────────────
  # Group 2: 丢包率指标
  # ────────────────────────────────────────────────────────────────────────
  - name: ping_lost
    interval: 3s
    rules:
      # 丢包标志 —— ping_latency_ms > 400 视为丢包 (1=丢包, 0=正常)
      - record: ping_lost_flag
        expr: ping_latency_ms > bool 400
      #  丢包率: leaf
      - record: ping_lost_by_leaf
        expr: |
          (
            sum by (tidc,tspine,tleaf) (sum_over_time(ping_lost_flag{strategy="01"}[3s])) 
              / 
            sum by (tidc,tspine,tleaf) (count_over_time(ping_latency_ms{strategy="01"}[3s]))
          ) * 100
      # [未使用] 丢包率: leaf max
      # - record: ping_lost_by_leaf_max
      #   expr: ping_lost_by_leaf
      # [未使用] 丢包率: leaf avg
      # - record: ping_lost_by_leaf_avg
      #   expr: ping_lost_by_leaf
      # [未使用] 丢包率: spine
      # - record: ping_lost_by_spine
      #   expr: |
      #     (
      #       sum by (tidc,tspine) (sum_over_time(ping_lost_flag{strategy="01"}[3s])) 
      #         / 
      #       sum by (tidc,tspine) (count_over_time(ping_latency_ms{strategy="01"}[3s]))
      #     ) * 100
      # [未使用] 丢包率: spine max
      # - record: ping_lost_by_spine_max
      #   expr: ping_lost_by_spine
      #  丢包率: idc
      - record: ping_lost_by_idc
        expr: |
          (
            sum by (tidc) (sum_over_time(ping_lost_flag{strategy="01"}[3s])) 
              / 
            sum by (tidc) (count_over_time(ping_latency_ms{strategy="01"}[3s]))
          ) * 100
      #  丢包率: idc max
      - record: ping_lost_by_idc_max
        expr: ping_lost_by_idc
      #  丢包率: 整体
      - record: ping_lost_overall
        expr: |
          (
            sum(sum_over_time(ping_lost_flag[3s])) 
              / 
            sum(count_over_time(ping_latency_ms[3s]))
          ) * 100
          
  # ────────────────────────────────────────────────────────────────────────
  # Group 3: 机房及及机房间网络指标
  # ────────────────────────────────────────────────────────────────────────
  - name: ping_idc
    interval: 10s
    rules:
      # 机房间时延
      - record: ping_idc_latency_avg
        expr: avg by (tidc) (ping_latency_ms{strategy!="01"} <= 400)
      # [未使用] 机房间时延
      # - record: ping_idc_latency_max
      #   expr: max by (tidc) (ping_latency_ms{strategy!="01"} <= 400)
      - record: ping_idc_latency_p99
        expr: quantile by (tidc) (0.99, ping_latency_ms{strategy!="01"} <= 400)

      # 机房间
      - record: ping_idc_lost
        expr: |
          (
            sum by (tidc) (sum_over_time(ping_lost_flag{strategy!="01"}[10s])) 
              / 
            sum by (tidc) (count_over_time(ping_latency_ms{strategy!="01"}[10s]))
          ) * 100
      # 机房间网络    
      - record: ping_idc_link_status
        expr: |
          (
            (quantile by (sidc,tidc) (0.99, ping_latency_ms{strategy!="01"}) > 150) * 3
          ) or (
            (quantile by (sidc,tidc) (0.99, ping_latency_ms{strategy!="01"}) > 50) * 2
          ) or (
            quantile by (sidc,tidc) (0.99, ping_latency_ms{strategy!="01"}) * 0 + 1
          )

  # ────────────────────────────────────────────────────────────────────────
  # Group 4: 同机房Leaf之间延迟指标
  # ────────────────────────────────────────────────────────────────────────
  - name: ping_leaf_latency
    interval: 10s
    rules:
      # 同机房 Leaf 之间： 平均
      - record: ping_leaf_avg
        expr: avg by (tidc,sleaf,tleaf) (ping_latency_ms{strategy="01"}<= 400)
      # 同机房 Leaf 之间： 最大
      - record: ping_leaf_max
        expr: max by (tidc,sleaf,tleaf) (ping_latency_ms{strategy="01"}<=400)
      - record: ping_leaf_max_all
        expr: max by (tidc,sleaf,tleaf) (ping_latency_ms{strategy="01"}<=400)  
      # 同机房 Leaf 之间： 99分位
      - record: ping_leaf_p99
        expr: quantile by (tidc,sleaf,tleaf) (0.99, ping_latency_ms{strategy="01"}<=400)

# ────────────────────────────────────────────────────────────────────────
  # Group 5: 同机房Leaf之间丢包率指标
  # ────────────────────────────────────────────────────────────────────────
  - name: ping_leaf_lost
    interval: 3s
    rules:
      # 同机房 Leaf 之间丢包率
      - record: ping_leaf_lost
        expr: |
          (
            sum by (tidc,sleaf,tleaf) (sum_over_time(ping_lost_flag{strategy="01"}[3s]))
              /
            sum by (tidc,sleaf,tleaf) (count_over_time(ping_latency_ms{strategy="01"}[3s]))
          ) * 100
